import os
# print(os.getcwd())
# os.chdir("C://")
# print(os.getcwd())
# f=open("harry.txt")
# print(os.listdir("C://"))
# os.mkdir("This")
# os.makedirs("This/That")
# os.rename("harry.txt","codewithharry.txt")
# print(os.environ.get("path"))
# print(os.path.join("C://","/harry.txt")

print(os.path.exists("C://harry"))
print(os.path.isdir("C://Program Files"))
print(os.path.isfile("C://Program Files"))