mystr="Harry is a good boy"
print(len(mystr))
print(mystr[0:20:2])
print(mystr.endswith("bot"))
print(mystr.count("o"))
print(mystr.capitalize())
print(mystr.replace("is","are"))
print(mystr.find("is"))
print(mystr.find("good"))
print(mystr.lower())
print(mystr.upper())
